### ISSUE TITLE
Ability to protonate pnictogens.

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/primarydock#107]
Look at this dock result, with all but one pose agreeing that the acid group of the ligand would be near HIS107:

[OR51E1_butyrate.test.dock.txt](https://github.com/primaryodors/primarydock/files/9244738/OR51E1_butyrate.test.dock.txt)

Though histidine is not normally protonated at biological pH, its proximity (within _DEFAULT_INTERA_R_CUTOFF) to an anion means that it can protonate at its local pH. This should be modeled in the docker and computed as an ionic interaction.

Similarly, there are receptors for pyrazines that may involve an ASP or GLU in ligand binding, and would be capable of protonating one or both nitrogens of the pyrazine ring if the proximity condition is met.

It's worth noting that both pyrazines and SCFAs like butyric acid have very low detection thresholds, probably due to not only their ability to coordinate metals but also their ionic nature inside a receptor's binding pocket.

**Comment by primaryodors** [comment]
Take into account the pKa values for both the ligand and the amino acid side chains. Here's a table: https://www.vanderbilt.edu/AnS/Chemistry/Rizzo/stuff/AA/AminoAcids.html

If the pKa of an acid group is <= that of a pnictogen, both moieties can ionize and form a salt bridge.
