### ISSUE TITLE
Clash calculations in differential dock.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#113]
This isn't quite right.  (See PR).

_Originally posted by @primaryodors in https://github.com/primaryodors/primarydock/pull/111#discussion_r939528934_

Clash calculation should still happen once per multiple Molecule* loop. Something else is causing the excessively large output numbers, because they still occur even with the function argument forced to false. Don't set it to false, but use a debugging compiler switch to uncover the actual root cause of the bad numbers.

**Comment by ssepeq** [comment]
It's happening because of real actual clashes. The candidate poses should be rejected by the algorithm, but aren't, because it's looking at the total overall system energy (generally anywhere from -7000 to beyond -11000) and not the ligand-residue clashes.
