### ISSUE TITLE
Predictions: The extrapolated active conformation is incorrect.

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/primarydock#128]
TMR7 is shown moving away from TMR3 when the opposite should happen. Seems to be part of a general moving away of TMR2, TMR1, and TMR7, opening the center of the protein, which would not happen in the real molecule. Additionally, there are motions of the extracellular ends of TMR5 and TMR6 that do not look correct.

Consequently, most predictions are coming up as inverse agonist.

**Comment by ssepeq** [comment]
https://pubs.acs.org/doi/full/10.1021/acs.chemrev.6b00177

The helices do not move as solid units; they bend near the middle. The outward movement of TMR6 is confined to the region below the 6.48 toggle switch, while the inward motion of TMR7 happens only near the cytoplasmic end. The region around the binding site changes very little.

Can retry ADRB2.pepd using the 3SN6 PDB instead of 4LDO but probably still won't get accurate results, even if modify the code to bend the helices.

It is going to be important to identify the toggle switch for ORs, as they do not have the conserved Trp6.48 of other GPCRs. See #97 for more information.

**Comment by primaryodors** [comment]
This was fixed in some recent PR or other.
