### ISSUE TITLE
Move water molecules in a path based dock.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#146]
One feature that would be good to add is in a path based dock, to move all the water molecules into the new node if it is more than a threshold distance from the previous node, and then settle them in so they aren't clashing.

If the new node is near enough the old node that their water spaces overlap, any water molecules inside that overlap should stay put and water molecules outside the new water space should be moved into a non-overlapping part of the new water space.

_Originally posted by @primaryodors in https://github.com/primaryodors/primarydock/pull/145#discussion_r1012497655_

**Comment by ssepeq** [comment]
This is partially addressed by: https://github.com/primaryodors/primarydock/commit/52e582b9f128482724cf0a97109bb54ffad168a5

However, we still want to add distance to the ligand target center as a reason to teleport, not just clashes and polar dissatisfaction.

**Comment by ssepeq** [comment]
Still happening: once a water molecule is deleted, it is unavailable for future poses. We should bring back deleted waters when a new pose begins.
