### ISSUE TITLE
Conjugated atoms to remain coplanar.

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/primarydock#15]
A "single" bond of a conjugated system, including a conjugated substitution of an aromatic ring, has partial double bond quality and should not be free to rotate. Examples of molecules showing this phenomenon include polyenes, cinnamaldehyde, and benzamidine. The phenomenon also extends to compounds like aniline, where the two hydrogens of the amino moiety have partial aromatic character and lie between the ring plane and their expected tetrahedral angles. With the exception of some of the hydrogens, all of these compounds should always remain coplanar.

Further info:

https://pubs.rsc.org/en/content/articlehtml/2015/cp/c5cp02582f

**Comment by ssepeq** [comment]
Still todo would be to force coplanarity of conjugated systems. For example, the SDF for citral retrieved from PubChem on 2017-03-13, has a C=CC=O moiety that deviates slightly from coplanar, which perhaps shoould be automatically fixed by the app.

**Comment by primaryodors** [comment]
Citral is warped that way because of steric hindrance; the methyl group on the beta carbon prevents the aldehyde moiety from laying flat to its conjugated bond.
