### ISSUE TITLE
Phenols should also remain coplanar.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#157]
Similar to #89 , if an aromatic ring or a double-bonded carbon has a hydroxyl or amine attached, the bond should not be able to rotate, although it can be allowed to flip. This does not apply if the substituent is e.g. an alkoxy group, since those apparently are free to rotate, so only enforce the rule if the attached pnictogen or chalcogen has bonds only to the sp<sup>2</sup> carbon and hydrogen.

**Comment by ssepeq** [comment]
The Bond::can_flip property was not tied to some of the relevant code (AABondDef does not even have a can_flip property!) so I am adding these in the amino acid class.

**Comment by ssepeq** [comment]
Testing the molecule class with:

`clear; make test/molecule_test && test/molecule_test 'Oc1ccccc1O' 'O'`
