### ISSUE TITLE
Receptor's ionic locks and h-bond locks should be maintained most of the time.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#162]
The helices of the receptor are held together by various bonds between residues such as salt bridges, hydrogen bonds, and possibly leucine zippers. These can pose a problem when, for example, a dock includes only one residue involved in a salt bridge, flexing it away from its stable position. To save processing time, only residues near the ligand are considered for ligand-residue interactions.

To solve this problem, the code might pre-scan the receptor for all such side chain to side chain interactions. Better yet would be to identify the strongest inter-residue binding for each side chain and refrain from flexing _any_ side chains unless doing so would offer them a better binding energy.

A good way to test this is with a protein such as OR1A1, where a conserved Asp or Glu in the 3.39 position (Asp111 in OR1A1) salt bridges to the His of the KAFSTCXSHL motif (His243 6.40). Docking a ligand such as citral or d-limonene often involves Asp111 but not His243, and any time such a dock shows the acid side chain pointing any direction but downward, it means the salt bridge has been broken, which would not occur in the real protein.

A test should also be found in which a salt bridge would be expected to break, perhaps involving an acidic ligand in a receptor that has a His in the binding pocket that normally hydrogen bonds to an Asn or Gln outside the pocket.

**Comment by primaryodors** [comment]
This just happened in a dock of estragole in OR1A1:

![image](https://user-images.githubusercontent.com/106125032/209417652-f864ca73-a4d1-4698-bc77-7da15adb8998.png)

**Comment by ssepeq** [comment]
The protein's entire set of residues is already being passed to multimol_conform() as "background" molecules. If Asp111 is coming undone from His243, it's happening because the docker isn't finding the salt bridge as having the best binding energy.

**Comment by ssepeq** [comment]
Docking estragole in OR1A1 doesn't seem to still be doing this. Was the dock made since the most recent PR merge?

**Comment by primaryodors** [comment]
It's also happening with musk ketone.

**Comment by ssepeq** [comment]
Unable to repro.
