### ISSUE TITLE
Centralize functionality from the method_*.php predictions.

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/primarydock#173]
Use the "scwhere" version as it is the most up to date with issues and PRs.

Code that selects receptor-ligand pairs, monitors other processes, runs primarydock, and writes output from primarydock, should all be moved to include files so that future improvements shall apply to all prediction methods.

**Comment by primaryodors** [comment]
Whichever method_*.php is the most recent, can be used as a template to write future method phps. All others are obsolete since the cryo-EM model.
