### ISSUE TITLE
Update functionality for tugs (related to #187)

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/primarydock#191]
The ssepeq-acv1st branch is doing fairly well docking adenosine in ADORA2. The base is pi-stacked to Phe168, the sugar has two hydroxyls pointed towards His278, but the amino group is not as close to Glu169 as in the X-ray model.

Unmet potential binding between ligand and side chains should elicit a tugging effect on the ligand, and on specific atoms of the side chains. The forces involved for the ligand would be linear transformational, barycentric rotational, atom-centric rotational, and flexional; the forces for the side chain would be flexional only.

Anisotropy would slightly complicate the algorithm, specifically: Ligand atom a "wants" side chain atom b to be at location wb; side chain atom b "wants" movable atom a to be at location wa; flexionals to bring b closer to wb; flexionals to bring a closer to wa; barycentric rotational to bring a closer to wa; linear transformation to bring a closer to wa; atom-centric rotational to bring wb closer to b.

Each of these forces would have a partial effect each iteration, i.e. they would not serve to instantly bring each atom right where it is "wanted", but rather to move atoms closer to their target locations, by a factor of between 0.1 and 0.333 each iteration.

**Comment by ssepeq** [comment]
The ssepeq-acv1st branch is giving inconsistent results docking adenosine in ADORA2, because of course it 🤬ing is.

**Comment by ssepeq** [comment]
Tugs have been implemented in one of the stale branches. The result is a disaster.

**Comment by primaryodors** [comment]
Closing this as tugs are unnecessary and in fact consistently produce worse results.
