### ISSUE TITLE
Prediction method to find the optimal receptor conformational change for each ligand individually.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#195]
Take a look at this article (open access): https://doi.org/10.3389/neuro.03.009.2009

> ...the DRY motif positioned at the cytoplasmic end of TM3 appears to be essential for G protein activation. Mutations within this motif caused either a constitutive activity or abolished G protein coupling (Imai et al., 2006). Based on this activation pattern, it has been proposed that upon ligand binding to the receptor, the third helix is displaced, thereby exposing the DRY motif and initiating the signal transduction pathway (Vaidehi et al., 2002; Katada et al., 2005).
>
> Interestingly, in vitro, ORs can couple to various G proteins, such as Gαolf, Gαs and Gα15 (Kajiya et al., 2001) and there are indications that the interaction of a receptor with a non-typical G protein, such as Gα15 instead of Gαolf, can alter the ligand specificity of an OR (Shirokova et al., 2005).

Elsewhere in the paper, it is hinted that the binding pocket of ORs is not as "rigid" as that of VN1Rs and therefore "can accommodate several ligands." Together these statements hint that, rather than trying to look for one active conformational change for all olfactory proteins, rather than even trying to suss out the changes for ORs individually, it may be more useful and more consistent with real protein behavior to identify the changes that would accommodate each ligand individually inside the binding pocket of each receptor. In other words, rather than a global activation matrix or a per-receptor matrix, the rotations and transformations might be unique to each protein-ligand pair.

Such a prediction method would employ a separate feature similar to, but independent of, the side chain flexion functionality. It would tweak the spatial locations and orientations of each TMR in either a trial-and-error or Monte Carlo manner during normal dock iterations. It would be activated with a .config file switch just like the existing flexion code is activated by the `FLEX` switch. Upon completed docking, the final transformations and rotations of the TMRs, relative to the original PDB, would be output as part of the dock result and included in both the command-line output and the .dock file. External code, such as a corr_*.php script, can analyze the conformational predictions of many dock results and look for Pearson correlations to empirical assay results.

**Comment by ssepeq** [comment]
Output metrics would include, for each TMR:

Linear "horizontal" motion towards/away from the center;
Angular "horizontal" motion relative to the center;
"Vertical" motion, i.e. towards the extracellular or cytoplasmic directions;
Rotation about the α-helical axis;
Rotation about the axis running from the center to the TMR;
Rotation about the axis perpendicular to the imaginary line from center to TMR.

The first two metrics can be represented by the symbols Δr and Δθ, respectively. The third would simply be Δy. For the last three metrics, the symbols can be Δα, Δφw, and Δφv.

The center could be considered as the mean xyz coordinate of all binding site residues' CB atoms (or CA in case of glycine).

**Comment by ssepeq** [comment]
TODO: There are a few new memory leaks to track down.

**Comment by ssepeq** [comment]
Took two tries (5 poses each) to get one pose with negative energy, but then it produced this amazing -97.8778 kJ/mol result.

[TAAR8_test.dock.txt](https://github.com/primaryodors/primarydock/files/10476639/TAAR8_test.dock.txt)

It seems to have moved TMR5 slightly inwards and towards TMR6, and rotated it about its long axis to bring Asp201 right up to the ligand.

**Comment by ssepeq** [comment]
Abandoned branch: https://github.com/primaryodors/primarydock/commit/f19034fbaaac3683d50d22b1f9e5a028a398d117

**Comment by ssepeq** [comment]
🟩🟩🟩

**Comment by ssepeq** [comment]
Some of the conformations have strong correlations:

![image](https://user-images.githubusercontent.com/66374250/215929501-10fd7da6-ea0e-4e48-9ccd-4e34691f0047.png)

But most are not this good, and there's very little consistency between different receptors which metrics give the best correlations.
