### ISSUE TITLE
Memory leak using RCSB PDB file.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#198]
- Download this PDB: https://www.rcsb.org/structure/5TGZ
- Download or obabel an sdf for one of its agonists, for example CBD or THC;
- Run the default primarydock.config with the 5tgz.pdb, the ligand sdf, 5 poses, 50 iters, search BB, appending the protein to the output file;
- Virtual memory usage will skyrocket and the computer will eventually hang.

Example command:
clear; bin/primarydock primarydock.config --prot pdbs/5tgz\ CB1.pdb --lig sdf/tetrahydrocannabinol.sdf --elim 99 --pose 5 --iter 50 --search BB --appendprot

Something is leaking memory so bad that PDBs straight out of RCSB are not usable with PrimaryDock. This is happening on the acvperlig branch, haven't tested it on stable. Also haven't tested with a PDB that was processed and output by Pepteditor.

**Comment by ssepeq** [comment]
5TGZ has a ligand in it, and is not a good raw PDB for docking anyway. CB1 can be successfully docked with THC by starting with the AlphaFold version and processing it with a .pepd script such as:

```
LOAD "pdbs/CB1_alphafold.pdb"

DELETE 0 112
DELETE 411 999

CENTER

REGION TMR1 113 143
REGION TMR2 151 179
REGION TMR3 186 218
REGION TMR4 231 252
REGION TMR5 273 314
REGION TMR6 332 366
REGION TMR7 374 399

REMARK 800 SITE BW 1.50 134
REMARK 800 SITE BW 2.50 163
REMARK 800 SITE BW 3.50 213
REMARK 800 SITE BW 4.50 241
REMARK 800 SITE BW 45.50 265
REMARK 800 SITE BW 5.50 292
REMARK 800 SITE BW 6.50 358
REMARK 800 SITE BW 7.50 394

UPRIGHT

HYDRO

SAVE "pdbs/CB1.pdb"
```

![image](https://user-images.githubusercontent.com/66374250/218234430-473fe346-2801-41bf-8d2b-d4c75281cfd1.png)

Output file attached:
[CB1_tetrahydrocannabinol.dock.txt](https://github.com/primaryodors/primarydock/files/10712373/CB1_tetrahydrocannabinol.dock.txt)

**Comment by ssepeq** [comment]
But it definitely should error out gracefully instead of gobbling up more and more virtual memory until the system freezes.

**Comment by ssepeq** [comment]
It was happening because the source PDB had negative residue numbers. The protein class has been modified to skip any input ATOM lines unless the residue number field contains only digits 0-9 and spaces.
