### ISSUE TITLE
An OR has been directly observed in its agonist bound state.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#200]
https://doi.org/10.1101/2022.12.20.520951
https://www.biorxiv.org/content/10.1101/2022.12.20.520951v1.full.pdf

Protein structure (not yet available): https://www.rcsb.org/structure/unreleased/8F76

The binding site does not consist of the residues identified by Man et al, meaning at least some ORs cannot be predicted using the current prediction attempts. All "method" and "corr" files located in the predict/ folder should now be assumed obsolete.

The binding of propionate in OR51E2 happens in a pocket delineated by F4.57 and L4.60 near the extracellular end of TMR4, aided by hydrogen bonds to Q45.53 and S6.55. H45.52 also appears to coordinate to the ligand, and is experimentally necessary for activation. The charged carboxylic acid group of propionate draws R6.59 nearer to TMR4, causing the extracellular end of TMR6 to rock inwards, accompanied by a counter motion of the cytoplasmic end. This appears to be what activates the receptor.

Propionate and acetate are small molecules that easily fit into this pocket. Larger carboxylic acids do not favor the active configuration. Mutagenesis of F4.57A causes the receptor to respond best to octanoic acid, while the L4.60A mutant prefers hexanoic acid, both in accord with the respectively larger pocket sizes. So it would seem that the ligand must make contact with a threshold surface area of the inside of the pocket, and be small enough to favor the inward motion of the top of TMR6, in order to be an agonist.

Accurate predictions will involve:
- Ensuring that the primarydock app correctly places the ligand into the pocket;
- Ensuring that agonist ligands favor the active state, defined by the rocking motion of TMR6;
- Testing this binding site, and other possible binding sites, for other empirical pairs;
- Identifying any other ways that a ligand might prefer the active position of TMR6.

Note that for thiol-sensitive receptors of the OR2 family, the presence of a copper binding site on TMR5 seems almost certain. How this will interact with the motion of TMR6 is another avenue to explore. Some ORs may have as yet undiscovered metal binding sites that may be revealed by a careful search.

This does not apply to TAARs, VN1Rs, or MS4As. TAARs probably function via their W6.48 trip switch, which ORs lack in favor of a FYG motif. The activation changes for VN1Rs and MS4As are still unknown.

**Comment by ssepeq** [comment]
It's important for prediction that the aliphatic chain of the propionate goes into the pocket defined by the residues from the paper: 4.57, 4.60, and 5.43. Activation seems to be dependent on van der Waals interactions with these side chains, and/or polar satisfaction effects that hold the aliphatic chain inside the pocket.

5.43 is part of an exposed aliphatic region along with 5.40, 5.44, 5.47, and 6.51. It may be that Arg6.59 acts as a ligand capture device, while the exposed aliphatic region orients the carbon chain into place, followed by ionic attraction between the ligand and the dual histidines 3.33 and 45.52, drawing the ligand and TMR6 inwards so that the hydrophobic chain moves into the hydrophobic pocket.

It is worth attempting a path based dock in which the ligand first binds to Arg6.59, then to the TMR5/TMR6 aliphatics, followed by activation of TMR6 and motion towards the two His residues, and finally ending in the observed binding pocket. Agonists such as propionate and acetate should make the move easily, while non-agonists such as octanoate would either clash, disturb the binding pocket side chains, or fail to strongly bind to TMR4.

**Comment by primaryodors** [comment]
What would happen if primarydock were set up to allow a "path based" dock where the ligand remains in place as the TM6 helix is incrementally rocked from its original position to some activation limit angle, repacking at each step, and the ligand bound energies compared over the entire sweep? Might agonists show a clear decrease of energy at higher angles, vs. non-agonists that would not demonstrate such a pattern?

**Comment by ssepeq** [comment]
The propionic acid test looks promising. Took more than 5000 seconds to run though.

[OR51E2_propionate.sweep.txt](https://github.com/primaryodors/primarydock/files/10975193/OR51E2_propionate.sweep.txt)

**Comment by ssepeq** [comment]
For octanoic acid, the numbers look good (no favorable trend for activation) but the ligand makes good contact with Arg262 even in the final path nodes.

[OR51E2_octanoic_acid.sweep.txt](https://github.com/primaryodors/primarydock/files/10975745/OR51E2_octanoic_acid.sweep.txt)

**Comment by ssepeq** [comment]
Hexanoic acid looks good, no particular trend.

[OR51E2_caproic acid.sweep.txt](https://github.com/primaryodors/primarydock/files/10976235/OR51E2_caproic.acid.sweep.txt)

**Comment by ssepeq** [comment]
Acetic acid shows a small preference for activation. Not enough Arg262 engagement though.

[OR51E2_acetic_acid.sweep.txt](https://github.com/primaryodors/primarydock/files/10980413/OR51E2_acetic_acid.sweep.txt)

**Comment by primaryodors** [comment]
The viewer changes implemented in #310, combined with the attached Pepteditor script, facilitate direct viewing of the active and inactive states superimposed. The conformational changes observed include:

- TMR1 pivots at the 1.54 position, bringing its extracellular end about 3A away from that of TMR2;
- TMR1 also moves about 0.25A in the EXR direction;
- TMR2 pivots at the 2.39 position, bringing its EXR end roughly 2.5A towards TMR1;
- TMR2 also moves approximately 0.6A in the EXR direction;
- TMR3 moves very slightly (maybe 0.25A) towards TMR7;
- TMR3 bends at 3.44 so that the CYT end moves 2.5A closer to TMR5 and the EXR end 2.5A roughly towards TMR5 except angled about 20deg outward;
- TMR4 overall moves slightly inward toward TMR3;
- TMR4 bends at 4.46 so that the EXR end moves inward 1.5A;
- TMR4 also slightly unravels around 4.60, producing a looser turn of the helix;
- TMR5 overall moves ~1.5A toward TMR6 and about 30deg outward;
- TMR5 can also be seen to bend at 5.49, bringing its CYT end a further ~1.7A outward;
- TMR6 moves outward about 0.25A and EXR-ward about 0.25A;
- TMR6 pivots at the 6.48 position, bringing its CYT end at least 6A outward, in roughly the direction away from the CYT loop between TMR2 and TMR3;
- in fish-like ORs at least, TMR6 also unwinds slightly at the EXR end to afford a better reach of Arg6.59 into the binding pocket;
- TMR7 moves about 0.8A toward TMR6;
- TMR7 pivots at the 7.49 position, bringing the EXR end about 3A away from the inactive EXR end of TMR2.

[model_comparison.pepd.txt](https://github.com/primaryodors/primarydock/files/12167889/model_comparison.pepd.txt)

**Comment by primaryodors** [comment]
The cryo-EM models of mTAAR9 suggest that receptor conformational changes for Golf coupling are considerably less pronounced than for Gαs coupling, resulting in a binding pocket that differs little from the inactive state other than the motion of TMR6.

mTAAR9 shows differences from hOR51E2 in how it changes shape to accommodate an agonist and Gαs. Specifically, TMR6 bends at the 6.48 position, bringing both ends outward from the center of the protein; TMR7 moves inward into space vacated by the ends of TMR6, nestling itself between TMR1, TMR2, and TMR6. For ORs, this inward transformation of TMR7 is impossible, since it would result in clashes with the EXR2 loop and helix.

**Comment by primaryodors** [comment]
Gαq coupling of BKRB2 shows mostly small transformations in the helices. TMR6 pivots about its EXR end to accommodate the G protein; TMR7 flexes near its CYT end to bring its final coil closer to TMR3, but then loosens this coil in order to rejoin the tail helix which is actually moved slightly outward.

The activation mechanism of this bradykinin receptor may be one of steric and anisotropic effects. Arg1 of the ligand just misses a pi-stack with Asp311, but L:Arg1 and L:Phe5 coordinate to R:Phe121. R:Trp113 and L:Pro7 form a van der Waals interaction. L:Phe8 coordinates to R:Phe286 and R:Tyr322, pushing them apart and perhaps forcing Ala321 downward towards Trp283(6.48), likely producing the observed receptor activation. Whether OR coupling to Gαq involves a similar mechanism is not certain, but seems unlikely if 6.48 serves as the pivot residue.

**Comment by primaryodors** [comment]
In angiotensin receptor AGTR1, L:Arg2 coordinates to R:Asp263 and R:Asp281, while the ligand's C terminus coordinates to R:Lys199 with a hydrogen bond to L:Tyr4. The side chain of the terminal L:Phe8 lies "under" the C terminus, forming a pi stack with R:Tyr113, but its most dramatic effect is to flex R:Leu112 entirely, causing it to point towards the center of the protein rather than toward TMR5. The resulting steric hindrance on Trp253(6.48) causes a bend in TMR6 at this location, moving the CYT end of TMR6 several A outward from center.

A similar change happens to the CYT end of TMR7 as we saw in BKRB2. Overall the Gαq-bound active state of AGTR1 resembles that of BKRB2, except for TMR6 bending in the middle rather than pivoting at the "top". It is reasonable that Gαq-compatible activation of ORs might also involve few large conformational changes beyond the pivot motion of TMR6.

**Comment by primaryodors** [comment]
FFAR1 bound to its fatty acid agonists shows a convergence of Arg183 from TMR5 and Arg258 from TMR7, accompanied by hydrogen bonding from Tyr240 and Asn244, both on TMR6. The ligand's hydrophobic chain is supported by Val84, Phe87, Leu138, Val141, Leu171, and Leu186. This receptor does not have an aromatic 6.48 residue (Val237 supplies the 6.48 position).

The binding of FFAR4 to its ligands is less clear; all models show the ligand carboxylic acid group between Glu204 and Asp208 on TMR5, with no basic or polar uncharged residues in reach. It is counterintuitive for a negatively charged group (pKa in the range of 4.0~5.5) to coordinate to negatively charged side chains.

**Comment by primaryodors** [comment]
Each GPCR has its own characteristic structural change upon activation by ligands. Consequently, studying the activation changes of non-olfactory GPCRs won't reveal anything about the activation mechanisms of ORs or TAARs. The model of OR51E2 from [8F76](https://www.rcsb.org/structure/8F76) is currently the only example of an active OR; the mouse TAAR9 models including [8IW1](https://www.rcsb.org/structure/8IW1) will suffice as prediction models for other TAARs.

The utility of non-olfactory GPCRs comes from comparing their couplings to different G proteins. The models for mTAAR9 only include Golf and Gs couples, while only Gs is available for a hOR51E2 model. This means that by comparing mTAAR9:Gs with mTAAR9:Golf, it should be possible to extrapolate hOR51E2:Golf. Similarly, if a non-olfactory GPCR has couplings available for Gs and Gq, or Gs and Go, then it can be possible to extrapolate Gq and Go couplings for OR and TAAR proteins.

**Comment by primaryodors** [comment]
There is no significant difference between Gq-bound and Go-bound states of the same receptor activated by the same ligand.


https://github.com/primaryodors/primarydock/assets/106125032/e5387d0c-d77a-4e0a-92cf-356c11713ae1


https://github.com/primaryodors/primarydock/assets/106125032/1dbe1bf2-072a-4727-a5fd-4243688acacd

**Comment by primaryodors** [comment]
Though the receptor backbone shapes are the same, the points of contact are different for the two G proteins. RCSB model 7F9Y reveals an ionic bond between Glu390 of the α subunit of the G protein and Lys329 of the receptor. It is part of a hydrophilic zone including R:Thr76, R:Ser327, and α:Asn392. A hydrophobic pocket is formed by α:Leu388, α:Leu393, R:Ile145, R:Ile235, R:Leu239, R:Met264, with an additional hydrogen bond between R:Thr261 and the C terminus of the G protein α subunit.
