### ISSUE TITLE
Result sorting algorithm bug.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#211]
It would appear that pose 1 of the output is always the first computed pose, and that only the remaining poses are sorted correctly:

```
Pose: 1
Total: -164.632

Pose: 2
Total: -197.141

Pose: 3
Total: -174.303

Pose: 4
Total: -98.3855

Pose: 5
Total: -83.9066
```

This could explain the discontinuity in some of the outputs, i.e. when pose 1 is missing because its energy level falls above the threshold for inclusion.

**Comment by ssepeq** [comment]
Works as intended. The sorting happens based not just on energy level but also polar satisfaction. Setting `polar_sat_influence_for_scoring = 0` in constants.h restores the sort to strictly using the total energy.
