### ISSUE TITLE
Disable or remove data from Kang (2020)

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#221]
None of the receptor-ligand pairs in this source agree with any empirical agonist pairs from other sources. There is simply no overlap.

The data appear to be more or less random, with little clustering of subfamily agonism like e.g. ionone for OR4D and the many agonists of OR2J and OR10G subfamilies.

The association of indole with OR2AT4 is interesting, but 2AT4 antagonists do not have a significant effect on the perception of indole's odor.

If possible, the data should be retained and simply not used in code, perhaps by something in predict/odorutils.php that removes this one source after loading the JSON data. If this is not practical, then a backup should be created before deleting the reference and its data.

**Comment by ssepeq** [comment]
While most of Kang's data do seem random, the pair of naphthalene in OR8G1 stands out as a much stronger response than the others. It looks like a real signal among a background of noise. The activation of 8G1 in response to naphthalene can be explained if the ligand were to form pi stacking bonds with F104(3.32) and Y259(6.55), within the mostly hydrophobic pocket of TMR3-5. Alternatively, the ligand might bridge the space between Y259 and H159(4.60), forming T-shaped pi stacking bonds with both residues' aromatic rings.
