### ISSUE TITLE
Keep an eye on these new cryo-EM models.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#256]
https://www.nature.com/articles/s41586-023-06106-4#data-availability

mTAAR9 with various ligands.

True it's a mouse protein, but it's easy to compare with the human analog.

**Comment by primaryodors** [comment]
> The mTAAR9 structures contain a deep and tight ligand-binding pocket decorated with a conserved D3.32W6.48Y7.43 motif, which is essential for amine odorant recognition. In the mTAAR9 structure, a unique disulfide bond connecting the N terminus to ECL2 is required for agonist-induced receptor activation.

**Comment by primaryodors** [comment]
The supplementary material is available for free and contains EC50 and curve top values. Since it's not for a human receptor, we can't add the data to the web app. However, the material shows that the ligand spectrum of mTAAR9 depends on which G protein is expressed.

The most abundant G protein, according to the supplementary tables, is Golf. mTAAR9 paired with Golf is sensitive to dimethylcyclohexylamine, phenethylamine, cadaverine, and either spermidine or spermine (it doesn't say, just calls it SPE). Two of the four agonists have fishy ammonia smells, and the other two have spermous smells. This hints that if hTAAR9 has a similar ligand spectrum, it may encode for either a fishy, ammonia, or spermous note depending on which agonist ligands it shares with mTAAR9.

Other G proteins present to a lesser degree include Go, Gi1, Gi3, and Gq, the last of which has mTAAR9 responding weakly to four more agonists, at least two of which have an ammonia-like odor note.

The takeaway here is that not only are there multiple possible active configurations per receptor, but also there are configurations active for some G proteins but not others, and these dissimilar conformers bind to different sets of agonists. So it is not sufficient to say that any given receptor is sensitive to an odorant, but rather that a receptor-G-protein pair is sensitive to that odorant, or a receptor can be sensitive to it depending on the G protein.

mTAAR9 did universally respond to cadaverine with all G proteins tested, with similar top and EC50 values each pair.

**Comment by ssepeq** [comment]
This is one of them:

https://www.rcsb.org/structure/8IW1
