### ISSUE TITLE
Create Master and Express unit tests.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#257]
>> It would appear that the Big Three on their own are not a sufficient test for each PR before merge. The ideal would be to have a master unit test that can be left running (overnight, if necessary) before merging, and a subset unit test of the most easily breakable things, that can be run periodically during development.

_Originally posted by @primaryodors in https://github.com/primaryodors/primarydock/issues/254#issuecomment-1566171331_

Let's create some kind of Master unit test that not only checks the Big Three, but also checks:
- Valid anisotropy results for several interacting atom pairs;
- Strengths of various noncovalent bonds;
- Dimerism of other molecule pairs besides ethanol-ethanol;
- At least one active soft dock, including Y6.55 coordination and R/K6.xx-D/E45.51 salt bridging;
- Atomic similarity;
- Amino acid similarity;
- Atom group selection;
- Amino group selection and group pairing;
- Amino acid tests;
- Point object tests;
- Protein test.

The Master unit test will be required for all PRs before merge, unless the PR does not affect any of the calculations in the classes, apps, or tests. E.g. a simple UI change would not require the Master test.

Let's also create an Express unit test containing only the most easily broken features, designed to not take more than a minute or two. (Details TBD.)

Importantly, the new unit tests would not stop once an error is reached, but would instead test each item in sequence and report a pass/fail for each item, then error out only at the end if one or more items failed.

PRs marked ready for review before the new tests are merged in, will not be held up by the new requirements. In other words, what's currently in review can proceed to approval and merge without having to wait for the unit tests to be finished.

**Comment by ssepeq** [comment]
We can add metal coordination to the test. #254 broke metallic interactions; #261 has a fix.

**Comment by primaryodors** [comment]
Let's resume these unit tests next; having them written and working will make it immensely easier to maintain the codebase and minimize bugs.
