### ISSUE TITLE
Adjust best binding algorithm to preferentially pair ligand aldehydes with basic side chains.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#258]
The best-binding is failing for aldehydes. It should favor pairing them with basic side chains, but it is pairing them to acids instead.

_Originally posted by @ssepeq in https://github.com/primaryodors/primarydock/issues/254#issuecomment-1565826290_

One example to test with may be Lys80 of OR1G1 with an octanal or decanal ligand. Another may be the His residues in the binding pocket of OR1A1 and any of that receptor's aldehyde agonist ligands.

**Comment by primaryodors** [comment]
#262

**Comment by ssepeq** [comment]
This might not be working.

Also, the same behavior should be applied to tumble spheres.

**Comment by primaryodors** [comment]
There is code to add a preference for basic side chains with aldehyde ligands, however aldehyde agonists of OR1A2 tend to make stronger bonds with S155 vs. K109 even when "stay close" paired with K109.
