### ISSUE TITLE
Amino tests are failing.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/primarydock#266]
`make amino_report` generates incorrect results for every amino acid. Would be a good idea to go ahead with the new percentage-based amino similarities after all.

This affects the best-binding algorithm, so should be addressed quickly.

**Comment by ssepeq** [comment]
Histidine sometimes resembles the basic aminos and sometimes resembles tyrosine in its affinity for polar vs. nonpolar side chains, changing form depending on pH: https://www.pnas.org/doi/10.1073/pnas.212643999

>> low-affinity peptides tightly bound at pH 7.0 can be released at pH 5.0. The imidazole group of histidine is the only amino acid side chain affected within this range. At pH 5.0 the group is positively charged, polar, and hydrophilic, whereas at pH 7.4 it is neutral, apolar, and hydrophobic.

Non-charged histidine even forms hydrophobic interactions with valine. And in the cryo-EM model of OR51E2, a histidine contacts the aliphatic chain of the propionate ligand instead of ionic bonding with the carboxylate group.

**Comment by ssepeq** [comment]
The pH of the surroundings of the olfactory receptors is approximately 5.5-6.5, and increases significantly during rhinitis. The pH is also usually higher in men than in women. https://doi.org/10.1046/j.1365-2273.1999.00223.x

Rhinitis can impede the ability to smell, and women usually have a better sense of smell than men. pH might be important to the proper functioning of olfactory receptors. At the very least, we should model the charge and polarity of histidine residues to a pH of 6.0, and it would also be a good idea to create a global pH variable that can be set from primarydock .config files and .pepd scripts as well as from the command line for all of the apps and utilities.

**Comment by ssepeq** [comment]
https://en.wikipedia.org/wiki/Catalytic_triad

>> The Serine-Histidine-Aspartate motif is one of the most thoroughly characterised catalytic motifs in biochemistry. ... The aspartate is hydrogen bonded to the histidine, increasing the pKa of its imidazole nitrogen from 7 to around 12.

TAARs have an aspartate hydrogen bonded to a histidine. When an amine ligand forms an ionic bond with the aspartate, pulling it towards the center of the binding pocket, the histidine must become hydrophobic and retreat into another part of the protein. This step is probably necessary to activate the receptor.
