### ISSUE TITLE
Allyl phenylacetate fails to dock in in OR1A1.

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/primarydock#269]
It's one of the receptor's strongest agonists.

Best binding pairs:
```
C5 C8 C9 C10 C12 C13 H21 H22 H23 H24 H25 C11 - Val254 Tyr258 
O4 C5 O6 - Asn155 His159 
C1 C2 H14 H15 H16 - Asn109
```

Would be better to coordinate C1-C2 to His159 and sandwich the aromatic ring between Phe206 and Tyr258. The ester oxygens could then reach Asn109 but probably not Asn155.

**Comment by primaryodors** [comment]
The ligand docks well enough in the hGNAS2 coupled PDB to cause a correct prediction.
