### ISSUE TITLE
G-protein coupling only works for ORs.

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/primarydock#281]
TAARs and VN1Rs are getting mangled and their helices broken apart. The current generate_couples code is only compatible with OR sequences; the other receptors must not have enough of the right contact residues.

Want to modify generate_couples to use a different set of contacts for TAARs, based on the experimental models in the `pdbs/` folder showing the coupling of mTAAR9 with G proteins.

Also want to modify the script to not attempt to couple MS4As, since these are not G-protein coupled receptors. Would like to devise a way to categorize receptors into categories including GPCR and "other" at least until the mechanism of MS4A activation and signalling is determined and those can be given their own category.

**Comment by primaryodors** [comment]
ORs can continue to process on the server while unit tests are being developed. This will become a critical fix in the foreseeable future.
