### ISSUE TITLE
couple.pepd: After homology, bend EXR ends of helices inward to make internal contacts.

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/primarydock#292]
ORs universally feature internal contacts between most or all of the following residues, given below as their Ballesteros-Weinstein numbers. TAARs and VN1Rs may also exhibit many of these same contacts:

```
1.60 - 7.66
2.39 - 3.46
2.42 - 3.42
2.53 - 3.32
3.30 - 4.54
3.36 - 6.47
3.40 - 6.48
3.56 - 5.60
45.47 - 6.62
45.49 - 7.41
```

Upon coupling a receptor to a G protein, the code should perform necessary transformations and/or rotations to reestablish any contacts that the homology algorithm may have broken.

If the adjustment is done in the `couple.pepd` script, then a new Pepteditor command will be required, one that calls AminoAcid::get_reach() on a specified residue of the current working strand.

Reestablishing broken contacts may result in clashes, in which case it will be important to evaluate whether to go ahead with the contact and move clashing regions out of the way, or ignore the contact if it offers only a small kJ/mol value.

**Comment by primaryodors** [comment]
Let's address the two critical priority issues before proceeding with this. They've been sitting untouched for a couple weeks now.
