### ISSUE TITLE
vdW bond distance is too large.

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/primarydock#293]
The most commonly cited figure is around 4A between atoms, depending on vdW radii. But going off of the chart on this page:

https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry_Textbook_Maps/Supplemental_Modules_(Physical_and_Theoretical_Chemistry)/Physical_Properties_of_Matter/Atomic_and_Molecular_Properties/Intermolecular_Forces/Specific_Interactions/Van_Der_Waals_Interactions

We can see that the distance given for van der Waals binding is in agreement with the above, while that for hydrogen bonds is given as 3A (0.3nm). But this is the distance between heavy atoms, not the distance between hydrogen and hbond acceptor.

In olfaction, the majority of vdW forces are between C-H...H-C atoms. Consulting `bindings.dat`, the C-H bond is 1.09A long. Consulting `elements.dat`, the vdW radius of hydrogen is 1.1A. 1.09+1.1+1.09 = 3.28, in good agreement with the usual 4A-give-or-take figure. This plus the fact that vdW repulsion is due to vdW radii makes it seem like ~4A is the distance between heavy atoms, not between H atoms.

Further support for this interpretation can be found in Billesbolle (2022) in supplementary figure 6a showing the propionate ligand right up against residues of the binding pocket:

https://www.nature.com/articles/s41586-023-05798-y/figures/11

This figure does show carbon atoms at distances of more than 3A apart, but their hydrogen atoms are much closer together.

So I think the value in the `distance` column for vdW bonds in `bindings.dat` should be less than 4A.

**Comment by ssepeq** [comment]
Using the coordinates in RCSB 8f76.pdb, of the ligand position shown in the above image, atom C3 of the propionate is indeed about 4A from the nearest atoms of Phe155 and Leu158, meaning the hydrogens are closer together.

```
ATOM	1186	CG	PHE	A	155	123,911	116,152	85,579	1	35,73	C
ATOM	1187	CD1	PHE	A	155	123,206	115,399	84,66	1	35,73	C
ATOM	1188	CD2	PHE	A	155	124,186	115,594	86,814	1	35,73	C
ATOM	1189	CE1	PHE	A	155	122,755	114,137	84,977	1	35,73	C
ATOM	1190	CE2	PHE	A	155	123,746	114,322	87,123	1	35,73	C
ATOM	1191	CZ	PHE	A	155	123,027	113,6	86,206	1	35,73	C
...											
ATOM	1215	CG	LEU	A	158	123,469	117,023	81,018	1	42,24	C
ATOM	1216	CD1	LEU	A	158	122,15	117,122	81,738	1	42,24	C
ATOM	1217	CD2	LEU	A	158	123,571	115,737	80,23	1	42,24	C
...											
HETATM	8171	C1	PPI	A	401	119,527	112,795	80,088	1	41,9	C
HETATM	8172	C2	PPI	A	401	119,64	113,677	81,342	1	41,9	C
HETATM	8173	C3	PPI	A	401	121,007	113,588	81,921	1	41,9	C
HETATM	8174	O1	PPI	A	401	119,996	113,213	79,019	1	41,9	O
HETATM	8175	O2	PPI	A	401	118,942	111,694	80,243	1	41,9	O

-----

ATOM	1187	CD1	PHE	A	155	2,20	1,81	2,74	3,95
ATOM	1189	CE1	PHE	A	155	1,75	0,55	3,06	3,56

ATOM	1216	CD1	LEU	A	158	1,14	3,53	-0,18	3,72
ATOM	1217	CD2	LEU	A	158	2,56	2,15	-1,69	3,75
```

**Comment by primaryodors** [comment]
Would be best to avoid reproducing copyrighted images. Not that there's anything desirable about journals putting scientific data behind paywalls, but why take the risk. This particular image is publicly available so I've edited your post to include a link instead.

That said, you raise a very good point.

**Comment by primaryodors** [comment]
There is now a `vdW-bond-distance` branch with the requested change. Please check out the branch and test it to make sure it passes unit tests, including a visual inspection of the output SDF and output dock files. If it looks good, go ahead and merge it into your working branch for #290.

**Comment by ssepeq** [comment]
Too close. The alcohols' carbons are 3.0A apart.

**Comment by ssepeq** [comment]
Also on PDB output the ASCII 3-letter bug seems to have returned.

**Comment by primaryodors** [comment]
When you fix the 3-letter bug, let's add a unit test to make sure it doesn't recur.
