### ISSUE TITLE
Allow Ballesteros-Weinstein numbering for pocket center and path node selection.

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/primarydock#97]
This will require BW numbers to be added to the included PDB files.

**Comment by primaryodors** [comment]
Should also fix the BW numbering for TMR6 of ORs. There seems to be some confusion about the exact numbering; most ORs have two Y residues stacked seven residues (two full α-helix turns) one above the other. One of these tyrosines should be 6.48, presumably the one closer to the cytoplasmic direction like the trip switch tryptophan of the TAARs, but I seem to recall seeing this residue in ORs as 6.40 in some papers, which doesn't line up with the sequence. Besides 6.48, TAARs usually have an aromatic 6.44 and 6.51, but no other conserved aromatic residue on that helix.

**Comment by ssepeq** [comment]
Here is the most likely alignment of the TMR6 region of ORs, TAARs, and VN1Rs.

```
                                +*      +
OR1A1             AFSTCGSHLTVVSLYYGTVMGTYFRP
OR1G1             AFSTCSSHLSVVSLFFGTSFCVDFSS
OR2B11            AFGTCSSHLMIVSLFYLPAIYMYLQP
OR3A1             AFSTCGSHLTVVAIFYGSGIFNYMRL
OR4D6             ALSTCTSHMLVVTLHFVPCVYIYCRP
OR5P3             AFSTCTSHLTAVTLFYGTITFIYVMP
OR6A2             AFSTCASHLTVVIIFYAASIFIYARP
OR7D4             AFSTCGSHLCVVSLFYGTGLGVYLSS
OR8D1             AFGTCSSHLMAVVIFFGSITFMYFKP
OR9G1             AFSTCSSHLTSVTLYYGSILYIYALP
OR10G7            AFQTCASHCIVVLCFFGPGLFIYLRP
OR11H12           AFSTCGSHLAVVSLCYSSLMVMYVSP
OR12D2            ALSTCASHFMVVILFYAPVLFTYIHP
OR13C3            AFSTCSAHLTVVIIFYGTIFFMYAKP
OR14A2            AFSTCFPHLTVFTVFIITAYFVYLKP
OR51E2            AFGTCVSHIGVVLAFYVPLIGLSVVH
OR52D1            ALSTCGSHIGIILVFYIPAFFSFLTH
OR56A4            ALSTCGSHFILILFFSTVLLVLVITN

* = the residue that is usually Y, and when mutated
from Y to F results in approximately one tenth the
odorant sensitivity.

+ = other residues that are often aromatic.

                             +   *  +
TAAR5                 LGIAVGIYLLCWLPFTIDTMVDS
TAAR6                 LGVTVVAFMISWLPYSIDSLIDA
TAAR8                 LGVTVLAFVISWLPYTVDILIDA      

* = 6.48.

                                 +
VN1R1    SCRPSQEARATHTIMVLVSSFFVFYSVHSFLTIWTTV
VN1R2    YPNSSPGNRAIQSILALVSTFALCYALSFITYVYLAL
VN1R3    SARSSPESRVTQSILVLVST  LCYFTRSPPSLHMSL
VN1R4    SPRASPENRATQSILILVSTFVSSYTLSCLFQVCMAL
VN1R5    CPRVSPVKRASQAILLLVSFVFT YWVDFTFSFSGGV
```

This would have the C/SWLPF/Y motif of the TAARs align to FYGxx of the ORs, making ORs' 6.50 not a conserved residue. However, the Y/FxxxWxxF/Y triad of TAARs stacks up neatly in much the same way as the two tyrosines in FYGxxxxxY of ORs. Ultimately, though, the W of TAARs is located about as far from the extracellular end of TMR6 as the FYG motif of ORs, so the assignment of C/SWL equivalent to FYG is supported by both structural and functional equivalence.

In the case of the VN1Rs, the conserved tyrosine seems to stand alone without a motif. It is located a varying distance from an SPRxSPxxRATQSILVLVSTF motif, implying that the alignment on the Y might be illusory, though no other candidate residue is an obvious fit for the 6.48 position.
